apiVersion: apps/v1
kind: Deployment
metadata:
  name: spamrs
  labels:
    app: spamrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spamrs
  template:
    metadata:
      labels:
        app: spamrs
    spec:
      containers:
      - name: spamrs
        image: registry:5000/spamrs:latest
        imagePullPolicy: Always
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: LOKI_ENDPOINT
            value: "http://grafana-loki-gateway.grafana/loki/api/v1/push"
          - name: K8S_NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"